# Generated by Django 3.1.3 on 2020-11-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='customer_need',
        ),
    ]
