# Generated by Django 3.1.3 on 2020-11-27 02:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201127_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Audio Interface', 'Audio Interface'), ('Airbags', 'Airbags'), ('Air conditioning', 'Air conditioning'), ('Seat Heating', 'Seat Heating')], max_length=53),
        ),
    ]
